Import Debian changes 1.0.0.50-1
steam (1.0.0.50-1) unstable; urgency=medium

  * New upstream release.
  * Use C locale by default (closes: #764311)
  * Better fix for steam including libstdc++ (closes: #781454).
  * Install steam executable to /usr/lib/steam (closes: #776183).
  * More robust handling of debconf selections (closes: #772598).
    - Thanks to Chris Kuehl.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -3,24 +3,22 @@
 export DH_VERBOSE=1
 
 uversion=$(shell uscan --report | head -2 | tail -1 | cut -d\  -f7 | cut -d, -f1)
-keepers=icons lib steam.6 steam.real steam.desktop steam_install_agreement.txt
-
-files=$(shell find debian -name \*.i386 | sed s/\\.i386//g)
-
+keepers=icons lib steam.6 steam steam.desktop steam_install_agreement.txt
 orig=../steam_$(uversion).orig.tar.xz
 dest=../steam-$(uversion).orig
 
 %:
 	dh $@
+ifneq ($(DEB_BUILD_ARCH), i386)
+	@echo "error: $(DEB_BUILD_ARCH) is not a supported architecture"
+	@exit 1
+endif
 
 override_dh_auto_configure:
 	python debian/scripts/templates-helper
-ifeq ($(DEB_BUILD_ARCH), i386)
-	for file in $(files); do cp $$file.i386 $$file; done
-endif
 
 override_dh_clean:
-	dh_clean -- debian/templates $(files)
+	dh_clean -- debian/templates
 	python debian/scripts/copyright-helper \
 	    debian/copyright.in debian/copyright
 
@@ -33,7 +31,6 @@ get-orig-source:
 	tar xf ../steam_$(uversion).tar.gz --strip-components=1 -C $(dest)
 	rm -f $(dest)/steam
 	cd $(dest) && tar xf bootstrap*.tar.* --strip-components=1
-	mv $(dest)/steam $(dest)/steam.real
 	cd $(dest) && for file in *; do \
 	    echo $(keepers) | grep -q $$file || rm -rf $$file; done
 	tar cJf $(orig) $(dest)
